name: TSChests
version: '${project.version}'
main: sammy.tschests.TSChests
api-version: '1.20'
commands:
  tschest:
    usage: /tschest
    description: get a key that allows you to open chests for players
    permission: tschest.use
permissions:
  tschest.use:
    default: op